apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-menu-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: example-menu-web
  template:
    metadata:
      labels:
        app: example-menu-web
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: example-menu-web
        image: {{ .Values.menuWebService.image.repository }}:{{ .Values.menuWebService.image.tag }}
        ports:
        - containerPort: 3001
          name: example-menu-web
        env:
        - name: API_HOST_URL
          value: {{ .Values.app.env.api_host_url }}
        - name: API_HOST_PORT
          value: {{ .Values.app.env.api_host_port }}
        resources:
          requests:
            cpu: 1m
            memory: 64Mi
          limits:
            cpu: 10m
            memory: 128Mi 
        startupProbe:
          httpGet:
            path: /health
            port: 3001
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: example-menu-web
spec:
  type: {{ .Values.menuWebService.serviceType }}
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: example-menu-web
